version: '2'
services:
    mynotemaker-app:
        image: mynotemaker
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mynotemaker-postgresql:5432/mynotemaker
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mynotemaker-elasticsearch:9300
        ports:
            - 8080:8080
    mynotemaker-postgresql:
        extends:
            file: postgresql.yml
            service: mynotemaker-postgresql
    mynotemaker-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mynotemaker-elasticsearch
